
title: Yet Another Network Automation Blog
title_separator          : "-"
locale                   : "en-US"
author: Christian Adell Querol
email: chadell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog is about sharing my thoughts and learnings about how to make IT infrastructures (specially Networking) easier and more agile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chadell.github.io"
github_username:  chadell
twitter_username: chadell0
linkedin_username: christianadell

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: chadell

google_analytics: UA-119143430-1

exclude:
  - Gemfile
  - Gemfile.lock

# Custom site configuration
lang: en

defaults:
  - scope:
      path: ""
    values:
      lang: "en"
  - scope:
      path: "assets/img"
    values:
      image: true
